#!/usr/bin/env python3
"""Turns a nav2 occupancy grid (.pgm + .yaml) into a Gazebo world of wall boxes.

The world is emitted in MAP coordinates, so the Gazebo world frame and the
navigation map frame coincide and the poses in areas_<map>.json apply unchanged.

    ros2 run frida_gz_sim world_from_map.py \
        <map_context>/maps/robocup2026_1.yaml worlds/arena_robocup2026_1.sdf
"""

import argparse
import os
import sys

import numpy as np
import yaml


def read_pgm(path: str) -> np.ndarray:
    """Read a binary (P5) PGM into a height x width array of grey values."""
    with open(path, "rb") as f:
        if f.readline().strip() != b"P5":
            raise ValueError(f"{path} is not a binary PGM")
        line = f.readline()
        while line.startswith(b"#"):
            line = f.readline()
        width, height = (int(v) for v in line.split())
        maxval = int(f.readline())
        if maxval > 255:
            raise ValueError("16-bit PGMs are not supported")
        return np.frombuffer(f.read(width * height), dtype=np.uint8).reshape(
            height, width
        )


def merge_rectangles(occupied: np.ndarray) -> list:
    """Greedy-merge occupied cells into (row0, col0, row1, col1) rectangles."""
    grid = occupied.copy()
    height, width = grid.shape
    rects = []
    for row in range(height):
        col = 0
        while col < width:
            if not grid[row, col]:
                col += 1
                continue
            # Widest run of occupied cells starting here
            end = col
            while end + 1 < width and grid[row, end + 1]:
                end += 1
            # Tallest block of the same width below it
            bottom = row
            while bottom + 1 < height and grid[bottom + 1, col : end + 1].all():
                bottom += 1
            grid[row : bottom + 1, col : end + 1] = False
            rects.append((row, col, bottom, end))
            col = end + 1
    return rects


def box_xml(index: int, center, size, wall_height: float) -> str:
    pose = f"{center[0]:.4f} {center[1]:.4f} {wall_height / 2:.4f} 0 0 0"
    dims = f"{size[0]:.4f} {size[1]:.4f} {wall_height:.4f}"
    return f"""      <collision name="wall_{index}_collision">
        <pose>{pose}</pose>
        <geometry><box><size>{dims}</size></box></geometry>
      </collision>
      <visual name="wall_{index}_visual">
        <pose>{pose}</pose>
        <geometry><box><size>{dims}</size></box></geometry>
        <material>
          <ambient>0.55 0.55 0.58 1</ambient>
          <diffuse>0.72 0.72 0.75 1</diffuse>
          <specular>0.1 0.1 0.1 1</specular>
        </material>
      </visual>
"""


def build_world(map_yaml: str, world_name: str, wall_height: float) -> str:
    with open(map_yaml) as f:
        meta = yaml.safe_load(f)
    image = meta["image"]
    if not os.path.isabs(image):
        image = os.path.join(os.path.dirname(os.path.abspath(map_yaml)), image)
    resolution = float(meta["resolution"])
    origin_x, origin_y = float(meta["origin"][0]), float(meta["origin"][1])
    grid = read_pgm(image)
    if int(meta.get("negate", 0)):
        grid = 255 - grid
    height = grid.shape[0]
    # Trinary maps: 0 is occupied, 205 unknown, 254 free
    occupied = grid < int((1.0 - float(meta["occupied_thresh"])) * 255)

    boxes = []
    for index, (row0, col0, row1, col1) in enumerate(merge_rectangles(occupied)):
        x_min = origin_x + col0 * resolution
        x_max = origin_x + (col1 + 1) * resolution
        y_min = origin_y + (height - 1 - row1) * resolution
        y_max = origin_y + (height - row0) * resolution
        boxes.append(
            box_xml(
                index,
                ((x_min + x_max) / 2, (y_min + y_max) / 2),
                (x_max - x_min, y_max - y_min),
                wall_height,
            )
        )

    ground = max(grid.shape) * resolution * 1.5
    return f"""<?xml version="1.0"?>
<!-- Generated by scripts/world_from_map.py from {os.path.basename(map_yaml)} - do not edit by hand -->
<sdf version="1.9">
  <world name="{world_name}">
    <physics name="1ms" type="dart">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>

    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>

    <gravity>0 0 -9.81</gravity>
    <scene>
      <ambient>0.7 0.7 0.7 1</ambient>
      <background>0.8 0.85 0.9 1</background>
      <shadows>false</shadows>
    </scene>

    <light type="directional" name="sun">
      <cast_shadows>false</cast_shadows>
      <pose>0 0 12 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse>
      <specular>0.1 0.1 0.1 1</specular>
      <direction>-0.3 0.2 -0.9</direction>
    </light>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>{ground:.1f} {ground:.1f}</size></plane></geometry>
        </collision>
        <visual name="visual">
          <geometry><plane><normal>0 0 1</normal><size>{ground:.1f} {ground:.1f}</size></plane></geometry>
          <material>
            <ambient>0.35 0.35 0.36 1</ambient>
            <diffuse>0.45 0.45 0.47 1</diffuse>
          </material>
        </visual>
      </link>
    </model>

    <!-- Arena walls: {len(boxes)} boxes merged from {int(occupied.sum())} occupied cells -->
    <model name="arena_walls">
      <static>true</static>
      <link name="walls">
{"".join(boxes)}      </link>
    </model>
  </world>
</sdf>
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("map_yaml", help="nav2 map metadata YAML")
    parser.add_argument("output", help="SDF world file to write")
    parser.add_argument("--wall-height", type=float, default=1.2)
    parser.add_argument("--world-name", default=None)
    args = parser.parse_args()

    name = args.world_name or os.path.splitext(os.path.basename(args.output))[0]
    world = build_world(args.map_yaml, name, args.wall_height)
    with open(args.output, "w") as f:
        f.write(world)
    print(
        f"Wrote {args.output} ({world.count('<collision')} wall boxes)", file=sys.stderr
    )


if __name__ == "__main__":
    main()
