#!/usr/bin/env python3
"""
Fold run logs into a capability manifest: measured success rate and duration per skill.

The score-aware selector reads the output to decide what is worth attempting inside a
task's time budget. ROS-free — run it on a laptop over collected logs.

Usage:
    python3 fit_capabilities.py [--runs ~/frida_runs] [--out config/capabilities.yaml]
    python3 fit_capabilities.py --by object            # bucket pick stats by object
"""

import argparse
import glob
import json
import os
from collections import defaultdict
from typing import Any, Iterator

SUCCESS = "EXECUTION_SUCCESS"
DEFAULT_RUNS_DIR = os.path.expanduser("~/frida_runs")


def iter_skill_rows(runs_dir: str) -> Iterator[dict]:
    """Yield every skill row across every run log, newest last."""
    for path in sorted(glob.glob(os.path.join(runs_dir, "*.jsonl"))):
        with open(path, encoding="utf-8") as handle:
            for line in handle:
                line = line.strip()
                if not line:
                    continue
                try:
                    row = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if row.get("event") == "skill":
                    yield row


def percentile(values: list[float], fraction: float) -> float:
    """Nearest-rank percentile; good enough for the sample sizes we will have."""
    if not values:
        return 0.0
    ordered = sorted(values)
    index = min(len(ordered) - 1, int(round(fraction * (len(ordered) - 1))))
    return ordered[index]


def summarize(rows: list[dict]) -> dict[str, Any]:
    durations = [row["duration_s"] for row in rows]
    successes = sum(1 for row in rows if row["status"] == SUCCESS)
    return {
        "p": round(successes / len(rows), 3),
        "p50": round(percentile(durations, 0.50), 1),
        "p90": round(percentile(durations, 0.90), 1),
        "n": len(rows),
    }


def build_manifest(rows: list[dict], bucket_key: str | None) -> dict[str, Any]:
    by_skill: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        by_skill[row["skill"]].append(row)

    manifest: dict[str, Any] = {}
    for skill, skill_rows in sorted(by_skill.items()):
        entry: dict[str, Any] = {"default": summarize(skill_rows)}
        if bucket_key:
            buckets: dict[str, list[dict]] = defaultdict(list)
            for row in skill_rows:
                value = row.get("context", {}).get(bucket_key)
                if value is not None:
                    buckets[str(value)].append(row)
            contexts = [
                {"match": {bucket_key: value}, **summarize(bucket_rows)}
                for value, bucket_rows in sorted(buckets.items())
                if bucket_rows
            ]
            if contexts:
                entry["contexts"] = contexts
        manifest[skill] = entry
    return manifest


def to_yaml(manifest: dict[str, Any]) -> str:
    """Hand-rolled emitter so this script needs no PyYAML on a bare laptop."""
    lines = [
        "# Generated by fit_capabilities.py — do not edit by hand.",
        "# p = success rate, p50/p90 = duration seconds, n = observations.",
        "",
    ]
    for skill, entry in manifest.items():
        lines.append(f"{skill}:")
        lines.append(f"  default: {_inline(entry['default'])}")
        contexts = entry.get("contexts", [])
        if contexts:
            lines.append("  contexts:")
            for context in contexts:
                stats = {key: value for key, value in context.items() if key != "match"}
                lines.append(f"    - match: {_inline(context['match'])}")
                lines.append(f"      stats: {_inline(stats)}")
        lines.append("")
    return "\n".join(lines)


def _inline(mapping: dict[str, Any]) -> str:
    return "{" + ", ".join(f"{key}: {value}" for key, value in mapping.items()) + "}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs", default=DEFAULT_RUNS_DIR, help="directory of *.jsonl run logs")
    parser.add_argument("--out", default="", help="write YAML here instead of stdout")
    parser.add_argument("--by", default="", help="context key to bucket by (e.g. object, location)")
    args = parser.parse_args()

    rows = list(iter_skill_rows(args.runs))
    if not rows:
        print(f"No skill rows found in {args.runs}. Run a task first.")
        return 1

    manifest = build_manifest(rows, args.by or None)
    text = to_yaml(manifest)

    if args.out:
        os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
        with open(args.out, "w", encoding="utf-8") as handle:
            handle.write(text)
        print(f"Wrote {args.out} from {len(rows)} skill calls across {_run_count(args.runs)} runs.")
    else:
        print(text)
    return 0


def _run_count(runs_dir: str) -> int:
    return len(glob.glob(os.path.join(runs_dir, "*.jsonl")))


if __name__ == "__main__":
    raise SystemExit(main())
