services:
  chromadb:
    profiles: [storing-groceries]

    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    environment:
      - ANONYMIZED_TELEMETRY=False
    volumes:
      - /src/hri/packages/embeddings/chromadb:/chroma/chroma
    restart: unless-stopped
