services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - ANONYMIZED_TELEMETRY=False
    volumes:
      - /src/hri/packages/embeddings/chromadb:/chroma/chroma
    restart: unless-stopped
    network_mode: host