services:
  chromadb:
    profiles: [storing, gpsr]
    network_mode: host
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"

    environment:
      - ANONYMIZED_TELEMETRY=False
      - CHROMA_HOST_PORT=8000
    volumes:
      - ./embeddings/chromadb:/chroma/chroma
    restart: unless-stopped

