services:
  chromadb:
    profiles: [storing-groceries, gpsr]
    network_mode: host
    image: chromadb/chroma:latest
    ports:
      - "8002:8000"
    environment:
      - ANONYMIZED_TELEMETRY=False
    volumes:
      - /src/hri/packages/embeddings/chromadb:/chroma/chroma
      - ./chromadb_config.yml:/config.yaml
    restart: unless-stopped

