# Speech variables
x-speech-devices:
  &speech-devices
  PULSE_SERVER: unix:/tmp/pulseaudio.socket
  PULSE_COOKIE: /tmp/pulseaudio.cookie

services:
  speech_devices:
    container_name: home2-hri-cpu-devices
    build:
      context: ../..
      dockerfile: docker/hri/Dockerfile.cpu
      args:
        BASE_IMAGE: roborregos/home2:cpu_base
    image: roborregos/home2:hri-cpu
    volumes:
      - ../../:/workspace/src
      - /tmp:/tmp

    network_mode: host
    user: ${LOCAL_USER_ID}:${LOCAL_GROUP_ID}
    privileged: true
    devices:
      - /dev:/dev
    environment:
      <<:
        - *speech-devices
      DISPLAY: ${DISPLAY}
    env_file:
      - .env
    tty: true
    command: [
        "bash",
        # "source /workspace/ws/devel/setup.bash && roslaunch hri recepcionist_laptop.launch",
      ]
