services:
  display:
    profiles: [receptionist, carry]

    container_name: home2-hri-display
    image: roborregos/home2:hri-display
    build:
      context: ../..
      dockerfile: docker/hri/Dockerfile.display
      args:
        BASE_IMAGE: roborregos/home2:cpu_base
        # BASE_IMAGE: roborregos/home2:cuda_base
    volumes:
      - ../../hri/display/:/app
    ports:
      - "3000:3000"
      - "8001:8001"
      - "8080:8080"
    command: ["/bin/bash", "/display-entrypoint.sh"]
