services:
  display:
    container_name: home2-hri-display
    image: roborregos/home2:hri-display
    build:
      context: ../..
      dockerfile: docker/hri/Dockerfile.display
      args:
        BASE_IMAGE: roborregos/home2:cpu_base
    volumes:
      - ../../hri/display/:/app
      - /dev:/dev
    environment:
      ROS_LOCALHOST_ONLY: 1
    ports:
      - "3000:3000"
      - "8001:8001"
      - "8080:8080"
    network_mode: host
    command: ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && npm run dev"]
