services:
  display:
    profiles: [receptionist, carry]

    container_name: home2-hri-display-l4t
    image: roborregos/home2:hri-display-l4t
    build:
      context: ../..
      dockerfile: docker/hri/Dockerfile.display
      args:
        BASE_IMAGE: roborregos/home2:l4t_base
    volumes:
      - ../../hri/display/:/app
      - /dev:/dev
    ports:
      - "3000:3000"
      - "8001:8001"
      - "8080:8080"
    network_mode: host
    command:
      [
        "/bin/bash",
        "-l",
        "-c",
        "source /opt/ros/humble/setup.bash && (ros2 run web_video_server web_video_server &) && npm run start",
      ]
