FROM python:3.9-slim

WORKDIR /app

COPY ../../hri/packages/speech/scripts/stt/requirements.txt .

# Install dependencies
RUN apt-get update && apt-get install -y \
    libsndfile1 \
    ffmpeg \
    portaudio19-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y ffmpeg