ARG BASE_IMAGE
FROM ${BASE_IMAGE}


###########################################
# HRI Dependencies
###########################################

RUN apt-get install -y python3-pyaudio

RUN apt-get update && apt-get install -y alsa-base alsa-utils gstreamer-1.0
RUN apt-get install -y libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 pulseaudio

RUN mkdir -p /workspace/requirements

# Python modules
COPY ../../hri/requirements/nlp.txt /workspace/requirements/nlp.txt
RUN pip install -r requirements/nlp.txt

COPY ../../hri/requirements/speech.txt /workspace/requirements/speech.txt
RUN pip install -r requirements/speech.txt

USER ros
RUN sudo usermod -aG audio ros

RUN sudo chown -R ros /usr/lib/python3.10/
RUN sudo chown -R ros /usr/local/lib/python3.10/

# RUN apt install -y espeak
# RUN pip install -U openai-whisper
