FROM ghcr.io/ggml-org/whisper.cpp:main

RUN apt-get update && \
    apt install -y build-essential

RUN cmake -B build -DWHISPER_SDL2=ON
RUN cmake --build build --config Release
RUN apt-get install sudo
RUN useradd -m -s /bin/bash whisper && \
    usermod -aG audio whisper && \
    echo 'whisper ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER whisper
RUN sudo usermod -aG audio whisper