ARG BASE_IMAGE
FROM ${BASE_IMAGE}


###########################################
# HRI Dependencies
###########################################

RUN mkdir -p /workspace/requirements

# Python modules
COPY ../../hri/requirements/nlp.txt /workspace/requirements/nlp.txt
COPY ../../hri/requirements/speech.txt /workspace/requirements/speech.txt

RUN pip install -r requirements/nlp.txt
RUN pip install -r requirements/speech.txt
RUN apt-get install -y python3-pyaudio

# RUN apt-get update && apt-get install -y alsa-base alsa-utils gstreamer-1.0
# RUN apt-get install -y libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
# RUN apt install -y espeak
# RUN pip install -U openai-whisper

# # Install Python 3.10 (Compatible with piper module, to run as subprocess)
# RUN add-apt-repository ppa:deadsnakes/ppa -y
# RUN apt install python3.10 -y
# RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
# RUN python3.10 -m pip install piper-tts

# # Install OpenAI in python 3.10
# RUN pip install openai

# ENTRYPOINT [ "/bin/bash", "-l", "-c" ]