FROM ollama/ollama:latest

# # Install curl to preload models
# RUN apt-get update || true && \
#     apt-get install -y --no-install-recommends gnupg curl ca-certificates && \
#     apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32 && \
#     apt-get update && \
#     apt-get install -y curl && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y curl && apt-get clean

