# Speech variables
x-speech-devices: &speech-devices
  PULSE_SERVER: unix:/tmp/pulse/pulseaudio.socket
  PULSE_COOKIE: /tmp/pulse/pulseaudio.cookie

services:
  speech_devices:
    container_name: home2-hri-cpu-devices
    build:
      context: ../..
      dockerfile: docker/hri/Dockerfile.cpu
      args:
        BASE_IMAGE: roborregos/home2:cpu_base

    image: roborregos/home2:hri-cpu
    volumes:
      - ../../:/workspace/src
      - ~/.config/pulse:/tmp/pulse
      - /dev:/dev
      - ./build:/workspace/build
      - ./install:/workspace/install
      - ./log:/workspace/log
      - ../frida_interfaces_cache:/workspace/frida_interfaces_cache

    network_mode: host
    privileged: true
    environment:
      ROS_LOCALHOST_ONLY: 1
      <<:
        - *speech-devices
      DISPLAY: ${DISPLAY}
    env_file:
      - .env
    tty: true
    entrypoint: ["bash", "-il", "-c"]
    command: ["${COMMAND:-/bin/bash}"]
