services:
  ollama:
    profiles: [receptionist, carry, gpsr, storing]

    container_name: home2-hri-ollama
    image: ollama:r36.4.3-ollama
    runtime: nvidia
    network_mode: host
    volumes:
      - ../../hri/packages/nlp/assets:/ollama
    environment:
      - OLLAMA_MODELS=/ollama
      - ROLE=${ROLE}
      # - ROS_LOCALHOST_ONLY: 1
    stdin_open: true
    tty: true
    entrypoint:
      ["/bin/bash", "-c", "/ollama/entrypoint.sh && tail -f /dev/null"]
