services:
  ollama:
    profiles: [receptionist, carry]
    
    container_name: home2-hri-ollama
    image: dustynv/ollama:r36.4.0
    runtime: nvidia
    network_mode: host
    volumes:
      - ../../hri/packages/nlp/assets:/ollama
    environment:
      - OLLAMA_MODELS=/ollama
    stdin_open: true
    tty: true
