services:
  ollama:
    profiles: [receptionist, carry, gpsr, storing]

    container_name: home2-hri-ollama
    image: dustynv/ollama:r36.4.0
    runtime: nvidia
    network_mode: host
    volumes:
      - ../../hri/packages/nlp/assets:/ollama
    environment:
      - OLLAMA_MODELS=/ollama
      - ROLE=${ROLE}
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash", "-c", "/ollama/entrypoint.sh && tail -f /dev/null"]
