services:
  postgres:
    image: roborregos/home2:hri-postgres

    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: home2-hri-postgres
    restart: "no"
    environment:
      POSTGRES_USER: rbrgs
      POSTGRES_PASSWORD: rbrgs
      POSTGRES_DB: postgres
    network_mode: host
    # volumes:
    #   - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"