services:
  stt-l4t:
    container_name: home2-hri-stt-l4t
    image: roborregos/home2:hri-stt-l4t
    runtime: nvidia
    build:
      context: ../..
      dockerfile: docker/hri/Dockerfile.stt-l4t
    ports:
      - 50052:50052
    volumes:
      - ../../hri/packages/speech/scripts/stt/:/app
      - ../../hri/packages/speech/speech/:/app/speech
    #command: [bash, -c, python3 -u Faster-whisper.py --port 50051 --model_size base.en]
    command: [bash, -c, tail -f /dev/null]
