services:
  stt-l4t:
    profiles: [receptionist, carry, gpsr, storing]

    container_name: home2-hri-stt-l4t
    user: root
    image: roborregos/home2:hri-stt-l4t
    runtime: nvidia
    build:
      context: ../..
      dockerfile: docker/hri/Dockerfile.stt-l4t
    volumes:
      - ../../hri/packages/speech/scripts/stt/:/app
      # - ../../hri/packages/speech/speech/:/app/speech
    environment:
      ROS_LOCALHOST_ONLY: 1
    network_mode: host
    command: [
        "bash",
        "-c",
        # "python3 -u faster-whisper.py --port 50052 --model_size base.en --log_transcriptions",
        "source /tmp/PyAV/scripts/activate.sh && deactivate && python3 whisper_online_server.py --min-chunk-size 1 --task transcribe --model large-v3-turbo --vad --backend faster-whisper --port 3000",
      ]
