services:
  stt-l4t:
    profiles: [receptionist, carry, gpsr]
    
    container_name: home2-hri-stt-l4t
    user: 1000:1000
    image: roborregos/home2:hri-stt-l4t
    runtime: nvidia
    build:
      context: ../..
      dockerfile: docker/hri/Dockerfile.stt-l4t
    ports:
      - 50051:50051
    volumes:
      - ../../hri/packages/speech/scripts/stt/:/app
      - ../../hri/packages/speech/speech/:/app/speech
    network_mode: host
    command: >
      bash -c "source /tmp/PyAV/scripts/activate.sh && deactivate && python3 -u faster-whisper.py --port 50051 --model_size large --log_transcriptions"
