services:
  stt:
    profiles: [receptionist, carry, gpsr, storing]

    container_name: home2-hri-stt
    image: roborregos/home2:hri-stt
    build:
      context: ../..
      dockerfile: docker/hri/Dockerfile.stt
    ports:
      - "50051:50051"
    volumes:
      - ../../hri/packages/speech/scripts/stt/:/app
      - ../../hri/packages/speech/speech/:/app/speech
    environment:
      ROS_LOCALHOST_ONLY: 1
    command:
      [
        "bash",
        "-c",
        "python3 -u faster-whisper-streaming.py --port 50051 --model large-v3-turbo --log_transcriptions",
      ]
