services:
  stt:
    container_name: home2-hri-stt
    image: roborregos/home2:hri-stt
    build:
      context: ../..
      dockerfile: docker/hri/Dockerfile.stt
    ports:
      - "50051:50051"
    volumes:
      - ../../hri/packages/speech/scripts/stt/:/app
      - ../../hri/packages/speech/speech/:/app/speech
    command: ["bash", "-c", "python3 -u Faster-whisper.py --port 50051 --model_size base.en"]
