services:
  stt:
    profiles: [receptionist, carry, gpsr, storing]

    container_name: home2-hri-stt
    image: roborregos/home2:hri-stt
    build:
      context: ../..
      dockerfile: docker/hri/Dockerfile.stt
    ports:
      - "50051:50051"
    volumes:
      - ../../hri/packages/speech/scripts/stt/:/app
      - ../../hri/packages/speech/speech/:/app/speech
    environment:
      ROS_LOCALHOST_ONLY: 1
    network_mode: host
    command:
      [
        "bash",
        "-c",
        # If transcription is too slow try tiny.en or if it's too imprecise try small.en
        # Larger models than these aren't recommended for CPU inference
        "python3 -u faster-whisper-streaming.py --port 50051 --model base.en --log_transcriptions",
      ]
