services:
  stt:
    container_name: home2-hri-stt-prod
    image: roborregos/home2:hri-stt-prod
    build:
      context: ../..
      dockerfile: docker/hri/Dockerfile.stt
    ports:
      - "50052:50052"
    volumes:
      - ../../hri/packages/speech/scripts/stt/:/app
      - ../../hri/packages/speech/speech/:/app/speech
    command:
      [
        "bash",
        "-c",
        "python3 -u faster-whisper.py --port 50052 --model_size base.en",
      ]
