services:
  tts:
    profiles: [receptionist, carry, gpsr]
    container_name: home2-hri-tts
    image: roborregos/home2:hri-tts
    build:
      context: ../..
      dockerfile: docker/hri/Dockerfile.tts
      args:
        BASE_IMAGE: roborregos/home2:cpu_base
        # BASE_IMAGE: roborregos/home2:cuda_base
    volumes:
      - ../../hri/packages/speech/scripts/tts/:/app
      - ../../hri/packages/speech/assets/downloads/offline_voice/:/app/models
    network_mode: host
    user: 1000:1000
    environment:
      PULSE_SERVER: unix:/tmp/pulse/pulseaudio.socket
      PULSE_COOKIE: /tmp/pulse/pulseaudio.cookie
    command: "python3 kokoro-tts.py"