command_interpreter:
  ros__parameters:
    base_url: "http://localhost:11434/v1"
    model: "llama3.2"
    speech_command_topic: "/speech/raw_command"
    publish_command_topic: "/task_manager/commands"
    temperature: 0.0
