# Exclude a variety of commonly ignored directories.
exclude = [
    "navigation",
    "robot_description",
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "*pb2*",
    "manipulation/packages/xarm_ros2",
    "manipulation/packages/pymoveit2",
    "manipulation/packages/gpd",
    "manipulation/packages/arm_pkg/arm_pkg"
]

