services:
  manipulation:
    container_name: home2-manipulation
    build:
      context: ../..
      dockerfile: ${DOCKERFILE:-docker/manipulation/Dockerfile.jetson}
      args:
        BASE_IMAGE: ${BASE_IMAGE:-roborregos/home2:cpu_base} 
    image: ${IMAGE_NAME:-roborregos/home2:manipulation-jetson}
    volumes:
      - ../../:/workspace/src/home2
      - /dev:/dev
      - /dev/video0:/dev/video0
      - /tmp:/tmp
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./build/:/workspace/build
      - ./install/:/workspace/install
      - ./log/:/workspace/log
      - ../frida_interfaces_cache:/workspace/frida_interfaces_cache
      - ./.bash_aliases:/home/ros/.bash_aliases
  
    network_mode: host
    user: 1000:1000
    privileged: true
    runtime: nvidia
    group_add: 
      - video

    environment:
      DISPLAY: ${DISPLAY}
      TERM: xterm-256color
      QT_X11_NO_MITSHM: 1
      QT_DEBUG_PLUGINS: 1
      ROS_LOCALHOST_ONLY: 1
      
    tty: true
    stdin_open: true    
    working_dir: /workspace
    # command: ["/bin/bash", "-i", "-l"]

    command: >    
      bash -c "${COMMAND:-/bin/bash}"