services:
  manipulation:
    container_name: home2-manipulation
    build:
      context: ../..
      dockerfile: ${DOCKERFILE:-docker/manipulation/Dockerfile.jetson}
      args:
        BASE_IMAGE: ${BASE_IMAGE:-roborregos/home2:cpu_base} 
    image: ${IMAGE_NAME:-roborregos/home2:manipulation-jetson}
    volumes:
      - ../../:/workspace
      - /dev:/dev
      - /dev/video0:/dev/video0
      - /tmp:/tmp
  
    network_mode: host
    user: 1000:1000
    privileged: true
    runtime: nvidia

    environment:
      DISPLAY: ${DISPLAY}
      TERM: xterm-256color
    tty: true
    stdin_open: true    
    working_dir: /workspace
    command: ["/bin/bash", "-i", "-l"]