# Sourced from /root/.bashrc on the first interactive shell, and directly by
# scripts/run_pipeline.sh when it is launched non-interactively. Idempotent:
# every step checks for its own result first, so re-running is cheap.

INITIAL_FOLDER="$(pwd)"
WORKSPACE_DIR="/workspace/src"
GIGA_DIR="$WORKSPACE_DIR/manipulation/packages/giga"
MODELS_DIR="$GIGA_DIR/data/models"

# Check if the GIGA submodule is checked out
if [ ! -d "$GIGA_DIR" ] || [ -z "$(ls -A "$GIGA_DIR" 2>/dev/null)" ]; then
    echo "GIGA submodule not found, initializing ..."
    cd "$WORKSPACE_DIR" && git submodule update --init --recursive -- manipulation/packages/giga
    echo "GIGA submodule initialized, continuing ..."
fi

# Check if the vgn python package (GIGA's actual code) is importable
if python3 -c "import vgn" >/dev/null 2>&1; then
    echo "GIGA (vgn) python package already installed, continuing ..."
else
    echo "Installing GIGA (vgn) python package ..."
    # Dependencies belong to the image, not to runtime. This used to run
    # `pip3 install -r requirements.txt` with every version pin stripped by
    # sed, which meant that any package missing from the image got whatever
    # release was current that day -- silently, and differently on each
    # machine. Two boxes on the same commit could end up with different
    # Open3D versions, and one of them linked a libusb the image never
    # installed, so `import open3d` failed on an installed open3d.
    #
    # Verify instead of mutate: if something is missing the image is wrong,
    # and the fix is to rebuild it, not to paper over it here with an
    # arbitrary version.
    missing=""
    for mod in numpy scipy pandas matplotlib open3d pybullet torch trimesh \
               urdfpy skimage tqdm tensorboard catkin_pkg pykdtree; do
        python3 -c "import $mod" >/dev/null 2>&1 || missing="$missing $mod"
    done
    if [ -n "$missing" ]; then
        cat <<EOF

ERROR: the image is missing these Python modules:$missing

They are installed by docker/manipulation/Dockerfile.giga-cpu (or
Dockerfile.giga). Rebuild the image rather than installing them here --
installing at runtime gives each machine different versions, which is how
the "import open3d fails although open3d is installed" bug happened.

    docker compose -f docker/manipulation/docker-compose-giga-cpu.yaml up -d --build

EOF
        return 1 2>/dev/null || exit 1
    fi

    pip3 install --no-build-isolation -e "$GIGA_DIR"

    echo "Building ConvONets compiled extensions ..."
    (cd "$GIGA_DIR" && python3 scripts/convonet_setup.py build_ext --inplace)
fi

# The object sets are versioned in the repo (data/urdfs/frida/{train,test}),
# but they are *prepared* assets -- decimated visual meshes plus convex or
# VHACD collision meshes, generated by scripts/prepare_object_assets.py from
# the raw scans. If they are missing, the repo checkout is incomplete; the
# raw scans are not in git (166MB) and live in $GIGA_DATA/mesh_sources.
if [ ! -d "$GIGA_DIR/data/urdfs/frida/train" ]; then
    cat <<EOF

WARNING: $GIGA_DIR/data/urdfs/frida/train is missing.
Data generation will fail without an object set. Either pull the repo
again, or regenerate the object sets from the raw scans:

    python3 scripts/prepare_object_assets.py /workspace/giga_data/mesh_sources/train data/urdfs/frida/train
    python3 scripts/prepare_object_assets.py /workspace/giga_data/mesh_sources/test  data/urdfs/frida/test

EOF
fi

# Pretrained checkpoints are only needed to run inference/evaluation against
# the paper's models -- training your own from scratch does not touch them,
# so this is a notice rather than a blocking check.
if [ ! -d "$MODELS_DIR" ] || [ -z "$(ls -A "$MODELS_DIR" 2>/dev/null)" ]; then
    cat <<EOF

Note: no pretrained models in $MODELS_DIR.
Not needed to train from scratch. To compare against the paper's
checkpoints, fetch them with:

    bash /workspace/src/docker/manipulation/fetch_giga_models.sh

EOF
else
    echo "GIGA pretrained models found in $MODELS_DIR, continuing ..."
fi

cd "$INITIAL_FOLDER"
