
INITIAL_FOLDER="$(pwd)"
WORKSPACE_DIR="/workspace/src"
GIGA_DIR="$WORKSPACE_DIR/manipulation/packages/giga"
MODELS_DIR="$GIGA_DIR/data/models"

# Check if the GIGA submodule is checked out
if [ ! -d "$GIGA_DIR" ] || [ -z "$(ls -A "$GIGA_DIR" 2>/dev/null)" ]; then
    echo "GIGA submodule not found, initializing ..."
    cd "$WORKSPACE_DIR" && git submodule update --init --recursive -- manipulation/packages/giga
    echo "GIGA submodule initialized, continuing ..."
fi

# Check if the vgn python package (GIGA's actual code) is importable
if python3 -c "import vgn" >/dev/null 2>&1; then
    echo "GIGA (vgn) python package already installed, continuing ..."
else
    echo "Installing GIGA (vgn) python package ..."
    pip3 install catkin_pkg
    grep -v '^torch==' "$GIGA_DIR/requirements.txt"
    pip3 install -r /tmp/giga_requirements_no_torch.txt
    rm -f /tmp/giga_requirements_no_torch.txt
    pip3 install --no-build-isolation -e "$GIGA_DIR"

    echo "Building ConvONets compiled extensions ..."
    (cd "$GIGA_DIR" && python3 scripts/convonet_setup.py build_ext --inplace)
fi

# The object sets are versioned in the repo (data/urdfs/frida/{train,test}),
# but they are *prepared* assets -- decimated visual meshes plus convex or
# VHACD collision meshes, generated by scripts/prepare_object_assets.py from
# the raw scans. If they are missing, the repo checkout is incomplete; the
# raw scans are not in git (166MB) and live in $GIGA_DATA/mesh_sources.
if [ ! -d "$GIGA_DIR/data/urdfs/frida/train" ]; then
    cat <<EOF

WARNING: $GIGA_DIR/data/urdfs/frida/train is missing.
Data generation will fail without an object set. Either pull the repo
again, or regenerate the object sets from the raw scans:

    python3 scripts/prepare_object_assets.py /workspace/giga_data/mesh_sources/train data/urdfs/frida/train
    python3 scripts/prepare_object_assets.py /workspace/giga_data/mesh_sources/test  data/urdfs/frida/test

EOF
fi

# Pretrained checkpoints are only needed to run inference/evaluation against
# the paper's models -- training your own from scratch does not touch them,
# so this is a notice rather than a blocking check.
if [ ! -d "$MODELS_DIR" ] || [ -z "$(ls -A "$MODELS_DIR" 2>/dev/null)" ]; then
    cat <<EOF

Note: no pretrained models in $MODELS_DIR.
Not needed to train from scratch. To compare against the paper's
checkpoints, fetch them with:

    bash /workspace/src/docker/manipulation/fetch_giga_models.sh

EOF
else
    echo "GIGA pretrained models found in $MODELS_DIR, continuing ..."
fi

cd "$INITIAL_FOLDER"
