geometry_msgs/PoseStamped pose
float32 velocity
float32 acceleration
string planner_id
bool apply_constraint
frida_interfaces/Constraint constraint
---
#result definition
int32 success
---
#feedback
string execution_state