var searchData=
[
  ['base_0',['base',['../namespacedetectors_1_1base.html',1,'detectors']]],
  ['demo_5fbecas_1',['demo_becas',['../namespacedemo__becas.html',1,'']]],
  ['demo_5fds4_2',['demo_ds4',['../namespacedemo__ds4.html',1,'']]],
  ['demo_5fface_3',['demo_face',['../namespacedemo__face.html',1,'']]],
  ['demo_5fmanager_4',['demo_manager',['../namespacedemo__manager.html',1,'']]],
  ['demo_5froborregosday_5',['demo_roborregosday',['../namespacedemo__roborregosday.html',1,'']]],
  ['detectors_6',['detectors',['../namespacedetectors.html',1,'']]],
  ['display_5freal_7',['display_real',['../namespacedisplay__real.html',1,'']]],
  ['display_5freal_5ftmr2025_8',['display_real_tmr2025',['../namespacedisplay__real__tmr2025.html',1,'']]],
  ['dlc_5flaunch_9',['dlc_launch',['../namespacedlc__launch.html',1,'']]],
  ['dock_5fto_5fhandle_10',['dock_to_handle',['../namespacedock__to__handle.html',1,'']]],
  ['doing_5flaundry_11',['doing_laundry',['../namespacedoing__laundry.html',1,'']]],
  ['doing_5flaundry_5ftask_5fmanager_12',['doing_laundry_task_manager',['../namespacedoing__laundry__task__manager.html',1,'']]],
  ['downsample_5fpc_13',['downsample_pc',['../namespacedownsample__pc.html',1,'']]],
  ['ds4_5fdemo_14',['ds4_demo',['../namespaceds4__demo.html',1,'']]],
  ['registry_15',['registry',['../namespacedetectors_1_1registry.html',1,'detectors']]],
  ['utils_16',['utils',['../namespacedetectors_1_1utils.html',1,'detectors']]],
  ['yolo_17',['yolo',['../namespacedetectors_1_1yolo.html',1,'detectors']]],
  ['yolo_5fe_18',['yolo_e',['../namespacedetectors_1_1yolo__e.html',1,'detectors']]]
];
