services:
  vision:
    container_name: home2-vision
    build:
      context: ../..
      dockerfile: ${DOCKERFILE:-docker/vision/Dockerfile.cpu}
      args:
        BASE_IMAGE: ${BASE_IMAGE:-roborregos/home2:cpu_base} 
    image: ${IMAGE_NAME:-roborregos/home2:vision-cpu}
    volumes:
      - ../../:/workspace
      - /dev:/dev
      # - /dev/video0:/dev/video0
  
    network_mode: host
    # user: 1000:1000
    privileged: true
    # devices:
    environment:
      DISPLAY: ${DISPLAY}
      TERM: xterm-256color
    tty: true
    # stdin_open: true    
    working_dir: /workspace
    command: ["/bin/bash", "-i", "-l"]
    # entrypoint: [ "bash", "-il", "-c"]
    # command: [
    #   "colcon build --symlink-install --packages-select task_manager frida_interfaces frida_constants speech nlp embeddings && source ~/.bashrc && bash"
    #   ]