FROM python:3.10-slim

WORKDIR /app

COPY ../../vision/requirements/moondream_server.txt .
RUN pip install --no-cache-dir -r moondream_server.txt

RUN apt-get update && apt-get install -y \
    wget \
    && rm -rf /var/lib/apt/lists/*
    
WORKDIR /app/vision/packages/moondream_run/moondream_server
RUN wget https://huggingface.co/vikhyatk/moondream2/resolve/9dddae84d54db4ac56fe37817aeaeb502ed083e2/moondream-2b-int8.mf.gz
WORKDIR /app