ARG BASE_IMAGE=ubuntu:22.04
FROM ${BASE_IMAGE}

# RUN mkdir -p /workspace/requirements
# RUN apt update && apt install -y ros-humble-cv-bridge

# Requirements
# COPY vision/requirements /workspace/requirements
# WORKDIR /workspace/requirements

# RUN pip install -r moondream.txt

# if BASE_IMAGE = roborregos/home2:cuda_base then run pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
RUN echo "${BASE_IMAGE}"
# RUN if [ "${BASE_IMAGE}" = "docker.io/roborregos/home2:cuda_base" ]; then \
#     echo "Installing PyTorch with CUDA support"; \
#     pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118; \
#     fi
# RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 

RUN pip install transformers
RUN pip install numpy==1.24
RUN pip install opencv-python
RUN pip install Pillow
RUN apt update
RUN apt install libvips-dev --no-install-recommends -y
RUN pip install pyvips
RUN pip install einops
RUN pip install accelerate

WORKDIR /workspace
# CV-bridge

# CycloneDDS
RUN sudo apt-get update -qq && sudo apt-get install -y -qq ros-humble-rmw-cyclonedds-cpp \
    && sudo rm -rf /var/lib/apt/lists/*
COPY docker/cyclonedds_setup.sh /usr/local/bin/cyclonedds_setup.sh
RUN sudo chmod +x /usr/local/bin/cyclonedds_setup.sh && sudo /usr/local/bin/cyclonedds_setup.sh
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
ENV CYCLONEDDS_URI=file:///etc/cyclonedds.xml
RUN echo "source /usr/local/bin/cyclonedds_setup.sh" >> /home/ros/.bashrc