services:

  moondream-server:
    container_name: home2-moondream-server
    image: roborregos/home2:moondream-server
    build:
      context: ../..
      dockerfile: docker/vision/Dockerfile.moondream.server
    ports:
      - "50052:50052"
    volumes:
      - ../../vision/packages/moondream_run/:/app
    working_dir: /app/moondream_server
    command: ["bash", "-c", "python3 -u server.py"]
