services:
  moondream-server:
    container_name: home2-moondream-server
    image: roborregos/home2:moondream-server
    profiles: ["moondream"]
    build:
      context: ../..
      dockerfile: docker/vision/Dockerfile.moondream.server
      args:
        # BASE_IMAGE: ${BASE_IMAGE:-roborregos/home2:cuda_base}
        BASE_IMAGE: roborregos/home2:l4t_base
    ports:
      - "50052:50052"
    volumes:
      - ../../vision/packages/moondream_run/:/workspace
      - /dev:/dev
      - /dev/video0:/dev/video0
      - /tmp:/tmp
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /workspace/moondream_server
    network_mode: host
    user: 1000:1000
    privileged: true
    runtime: nvidia
    group_add:
      - video
    environment:
      DISPLAY: ${DISPLAY}
      TERM: xterm-256color
      QT_X11_NO_MITSHM: 1
      QT_DEBUG_PLUGINS: 1
    tty: true
    stdin_open: true
    command: ["bash", "-c", "python3 -u server.py"]

  moondream-node:
    container_name: home2-moondream-node
    build:
      context: ../..
      dockerfile: docker/vision/Dockerfile.moondream
      args:
        BASE_IMAGE: ${BASE_IMAGE:-roborregos/home2:cpu_base}
    image: roborregos/home2:moondream-node
    profiles: ["moondream"]
    volumes:
      - ../../:/workspace
      - /dev:/dev
      - /dev/video0:/dev/video0
      - /tmp:/tmp
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./moondream/build:/workspace/build
      - ./moondream/install:/workspace/install
      - ./moondream/log:/workspace/log

    network_mode: host
    user: 1000:1000
    privileged: true
    runtime: ${RUNTIME:-}
    group_add:
      - video

    environment:
      DISPLAY: ${DISPLAY}
      TERM: xterm-256color
      QT_X11_NO_MITSHM: 1
      QT_DEBUG_PLUGINS: 1
      ROS_LOCALHOST_ONLY: 1

    tty: true
    stdin_open: true
    working_dir: /workspace
    # command: ["/bin/bash", "-i", "-l"]
    command: bash -c "source /opt/ros/humble/setup.bash && colcon build --packages-up-to moondream_run && source install/setup.bash && ros2 run moondream_run moondream_node.py"
    # command: bash -c "source /opt/ros/humble/setup.bash && source install/setup.bash && ros2 run moondream_run moondream_node.py"
