"""
Measured capability lookup: how well and how fast each skill actually works.

Generated by ``scripts/fit_capabilities.py`` from run logs — never hand-written. The
registry's priors fill in wherever measurements are thin, so a skill the robot has
barely attempted is not judged on two samples.
"""

import os
from dataclasses import dataclass
from typing import Optional

from task_manager.skills.registry import REGISTRY

# below this many observations, blend toward the registry prior
MIN_CONFIDENT_N = 5


@dataclass(frozen=True)
class Capability:
    p: float
    p50: float
    n: int = 0

    @property
    def confident(self) -> bool:
        return self.n >= MIN_CONFIDENT_N


class Manifest:
    """Skill -> measured success rate and duration, optionally per context."""

    def __init__(self, data: Optional[dict] = None):
        self._data = data or {}

    def lookup(self, skill: str, context: Optional[dict] = None) -> Capability:
        """Most specific measurement available, blended with the prior when thin."""
        entry = self._data.get(skill, {})
        measured = None

        if context:
            for candidate in entry.get("contexts", []):
                match = candidate.get("match", {})
                if all(str(context.get(key)) == str(value) for key, value in match.items()):
                    stats = candidate.get("stats", candidate)
                    measured = _capability(stats)
                    break

        if measured is None and "default" in entry:
            measured = _capability(entry["default"])

        prior = self._prior(skill)
        if measured is None:
            return prior
        if measured.confident:
            return measured
        return _blend(measured, prior)

    def _prior(self, skill: str) -> Capability:
        declared = REGISTRY.get(skill)
        if declared is None:
            return Capability(p=0.5, p50=20.0, n=0)
        return Capability(p=declared.prior_success, p50=declared.prior_duration_s, n=0)

    def known_skills(self) -> tuple:
        return tuple(sorted(self._data))

    def __contains__(self, skill: str) -> bool:
        return skill in self._data


def _capability(stats: dict) -> Capability:
    return Capability(
        p=float(stats.get("p", 0.5)),
        p50=float(stats.get("p50", 20.0)),
        n=int(stats.get("n", 0)),
    )


def _blend(measured: Capability, prior: Capability) -> Capability:
    """Weight the measurement by how much of MIN_CONFIDENT_N it has reached."""
    weight = measured.n / MIN_CONFIDENT_N if MIN_CONFIDENT_N else 1.0
    weight = max(0.0, min(1.0, weight))
    return Capability(
        p=measured.p * weight + prior.p * (1 - weight),
        p50=measured.p50 * weight + prior.p50 * (1 - weight),
        n=measured.n,
    )


def load_manifest(path: str) -> Manifest:
    """Load a capabilities YAML; an absent file yields a prior-only manifest."""
    if not path or not os.path.exists(path):
        return Manifest()
    import yaml

    with open(path, encoding="utf-8") as handle:
        return Manifest(yaml.safe_load(handle) or {})
