services:
  zed_ros2:
    image: zed_ros2_l4t_36.4.0_sdk_4.2.5
    runtime: nvidia
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - ROS_LOCALHOST_ONLY=1
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - /dev:/dev
      - /dev/shm:/dev/shm
      - /usr/local/zed/resources/:/usr/local/zed/resources/
      - /usr/local/zed/settings/:/usr/local/zed/settings/
    stdin_open: true
    tty: true
    command: "ros2 launch zed_wrapper zed_camera.launch.py camera_model:=zed2 publish_tf:=true"
