services:
  ei-inference-door:
    container_name: home2-hri-ei-door-l4t
    image: public.ecr.aws/g7a8t7v6/inference-container-jetson-orin-6-0:v1.92.11
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ../../../hri/packages/speech/assets/downloads/door/:/data/
    ports:
      - "1337:1337"
    command:
      - --model-file
      - /data/model.eim
      - --run-http-server
      - "1337"
      - --force-target
      - runner-linux-aarch64-jetson-orin-6-0
      - --force-variant
      - float32
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  ei-inference-kws:
    container_name: home2-hri-ei-kws-l4t
    image: public.ecr.aws/g7a8t7v6/inference-container-jetson-orin-6-0:v1.92.11
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ../../../hri/packages/speech/assets/downloads/kws/:/data/
    ports:
      - "1338:1338"
    command:
      - --model-file
      - /data/model.eim
      - --run-http-server
      - "1338"
      - --force-target
      - runner-linux-aarch64-jetson-orin-6-0
      - --force-variant
      - float32
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
