services:
  events:
    container_name: home2-hri-events-${ENV_TYPE:-cpu}
    build:
      context: ../../..
      dockerfile: docker/hri/dockerfiles/Dockerfile.events
      args:
        BASE_IMAGE: python:3.9-slim
    volumes:
      - ../../../hri/packages/speech/scripts/events/:/app/
    image: roborregos/home2:hri-events-${ENV_TYPE:-cpu}
    network_mode: host
    runtime: ${RUNTIME:-}
    user: ${LOCAL_USER_ID:-1000}:${LOCAL_GROUP_ID:-1000}
    privileged: true
    environment:
      TERM: xterm-256color
      TFHUB_CACHE_DIR: /app/models/
    tty: true
    command: "python3 -u events-detector.py --port 50053"
