services:
  llama:
    profiles: [hric, carry, gpsr, storing]
    container_name: home2-hri-llama-l4t
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.llamacpp
    image: roborregos/home2:hri-llama-l4t
    runtime: nvidia
    network_mode: host
    volumes:
      - ../../../hri/packages/nlp/assets:/root/.cache/huggingface
      - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra
    environment:
      ROLE: ${ROLE}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash", "/scripts/entrypoint.sh"]
