services:
  llm:
    profiles: [hric, carry, gpsr, storing]
    container_name: home2-hri-llamacpp-l4t
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.llamacpp
      args:
        BASE_IMAGE: dustynv/llama_cpp:gguf-r36.4.0

    image: roborregos/home2:hri-llamacpp-l4t
    runtime: nvidia
    network_mode: host
    volumes:
      - ../../../hri/packages/nlp/assets:/models
    environment:
      ROLE: ${ROLE}
    stdin_open: true
    tty: true
    entrypoint:
      ["/bin/bash", "-c", "/scripts/entrypoint.sh && tail -f /dev/null"]
