#goal definition
float32 timeout
string hotwords
float32 silence_time
float32 start_silence_time
---
#result definition
string transcription
string[] words
float32[] confidences
---
#feedback
string current_transcription