SPEAK_SERVICE = "/speech/speak"
STT_SERVICE_NAME = "/speech/STT"
KEYWORD_TOPIC = "/speech/kws"
COMMAND_INTERPRETER_SERVICE = "/nlp/command_interpreter"
EXTRACT_DATA_SERVICE = "/nlp/data_extractor"
SENTENCE_BUILDER_SERVICE = "/nlp/sentence_builder"
ITEM_CATEGORIZATION_SERVICE = "/nlp/item_categorization"
CONVESATION_SERVICE = "/nlp/conversation"
GRAMMAR_SERVICE = "/nlp/grammar"

ADD_ITEM_SERVICE = "/nlp/embeddings/add_item_service"
REMOVE_ITEM_SERVICE = "/nlp/embeddings/remove_item_service"
UPDATE_ITEM_SERVICE = "/nlp/embeddings/update_item_service"
QUERY_ITEM_SERVICE = "/nlp/embeddings/query_item_service"
BUILD_EMBEDDINGS_SERVICE = "/nlp/embeddings/build_embeddings_service"
