ARG BASE_IMAGE=nvidia/cuda:11.8.0-devel-ubuntu22.04 
FROM ${BASE_IMAGE}

USER ros
SHELL ["/bin/bash", "-c"]

RUN pip install --upgrade pip
RUN pip install pyserial 
RUN sudo apt update
RUN mkdir -p /workspace
WORKDIR /workspace 
COPY ./navigation /workspace/src
RUN cd /workspace/src && sudo apt update && sudo rosdep init && rosdep update
RUN rosdep install --from-paths . --ignore-src --skip-keys "frida_constants frida_interfaces" -y
RUN sudo rm -rf /workspace/src/
WORKDIR /workspace
