ARG BASE_IMAGE=ghcr.io/ggerganov/llama.cpp:server-cuda
FROM ${BASE_IMAGE}

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY scripts/llama-cpp-entrypoint.sh /scripts/entrypoint.sh
RUN chmod +x /scripts/entrypoint.sh
