ARG BASE_IMAGE=roborregos/home2:l4t_base
FROM ${BASE_IMAGE}

# Install dependencies
RUN apt-get update && apt-get install -y \
    libsndfile1 \
    libxml2-dev \
    portaudio19-dev \
    git \
    cmake \
    g++ \
    pkg-config \
    libx264-dev \
    && rm -rf /var/lib/apt/lists/*

# Install CTranslate2 from source
WORKDIR /tmp
RUN git clone --recursive https://github.com/OpenNMT/CTranslate2.git
WORKDIR /tmp/CTranslate2
RUN mkdir build
WORKDIR /tmp/CTranslate2/build
RUN cmake .. -DOPENMP_RUNTIME=NONE -DWITH_CUDA=ON -DWITH_MKL=OFF -DWITH_CUDNN=ON -DCUDA_ARCH_LIST="8.7"
RUN make -j4
RUN make install
RUN ldconfig
WORKDIR /tmp/CTranslate2/python
RUN pip install -r install_requirements.txt
RUN python3 setup.py bdist_wheel
RUN pip install dist/*.whl

# Install PyAV from source
WORKDIR /tmp
RUN git clone https://github.com/PyAV-Org/PyAV.git
WORKDIR /tmp/PyAV
RUN pip install virtualenv
RUN bash -c "source ./scripts/activate.sh && ./scripts/build-deps && make && deactivate && pip install ."

# Install additional Python dependencies
WORKDIR /app
COPY ../../hri/requirements/stt.txt requirements.txt
RUN python3 -m pip install --upgrade pip
RUN pip install --no-cache-dir -r /app/requirements.txt
RUN pip install --upgrade protobuf

COPY ../../hri/proto_interfaces /tmp/proto_interfaces
RUN pip install --no-cache-dir /tmp/proto_interfaces

RUN pip install --no-cache-dir --force-reinstall --no-deps /tmp/CTranslate2/python/dist/*.whl
