ARG BASE_IMAGE=ollama/ollama
FROM ${BASE_IMAGE}

# Install curl to preload models
RUN apt-get update && apt-get install -y curl && apt-get clean

# Copy entrypoint script into the image
COPY scripts/entrypointOllama.sh /scripts/entrypoint.sh
RUN chmod +x /scripts/entrypoint.sh