
ARG BASE_IMAGE=python:3.10-bookworm
FROM ${BASE_IMAGE}

WORKDIR /app

COPY hri/requirements/stt.txt requirements.txt

# Install dependencies
RUN apt-get update && apt-get install -y \
    portaudio19-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install requests==2.32.5

COPY hri/proto_interfaces /tmp/proto_interfaces
RUN pip install --no-cache-dir /tmp/proto_interfaces
