services:
  l4t_base:
    build:
      context: .
      dockerfile: Dockerfile.ROS-l4t
      args:
        BASE_IMAGE: ubuntu:24.04
        ROS_DISTRO: jazzy
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
    image: roborregos/home2:l4t_base
