geometry_msgs/PoseStamped pose
float32 velocity
float32 acceleration
float32 planning_time
int32 planning_attempts
float32 tolerance_position
float32 tolerance_orientation
string planner_id
string target_link
bool apply_constraint
frida_interfaces/Constraint constraint
---
#result definition
int32 success
---
#feedback
string execution_state