services:
  frida_interfaces_cache:
    build:
      context: .
      # Dockerfile.ROS is the same for both CPU and GPU
      dockerfile: ../Dockerfile.ROS
      args:
        BASE_IMAGE: ubuntu:22.04
    image: roborregos/home2:l4t_base

    container_name: home2-frida-interfaces-cache
    volumes:
      - ../../:/workspace/src
      - ./build:/workspace/build
      - ./install:/workspace/install
      - ./log:/workspace/log
    tty: true
    entrypoint: ["bash", "-il", "-c"]
    # command: ["bash"]
    command: ["source /opt/ros/humble/setup.bash && colcon build --packages-select frida_interfaces frida_constants xarm_msgs"]
