# QueryItem.srv
string[] query  # The search query
int16 topk #number of results 
string collection #return
---
string[] results  # List of results (documents) that match the query, top k
bool success  # Whether the operation was successful
string message  # A message describing the result
