keyword_spotting:
  ros__parameters:
    KEYWORD_DIR: "/workspace/src/hri/packages/speech/assets"
    audio_topic: "/rawAudioChunk"
    detection_publish_topic: "/keyword_detected"
    sensitivity: 0.6
