kws_eim:
  ros__parameters:
    EI_SERVER_URL: "http://localhost:1338"
    PROCESSED_AUDIO_TOPIC: REPLACE
    WAKEWORD_TOPIC: REPLACE
    detection_cooldown: 1.0
    SENSITIVITY_THRESHOLD: 0.35
    sample_rate: 16000
    window_size_s: 1.0
    hop_ratio: 0.25
    audio_gain: 1.0
    noise_label: "noise"
    SAVE_DETECTION_AUDIO: false
    AUDIO_SAVE_DIR: "/workspace/src/hri/packages/speech/assets/kws_detections"
