object_detector_node:
  ros__parameters:
    RGB_IMAGE_TOPIC : /raw_image
    DEPTH_IMAGE_TOPIC :  /zed/zed_node/depth/depth_registered
    CAMERA_INFO_TOPIC :  /zed/zed_node/depth/camera_info
    DETECTIONS_TOPIC : /detections
    DETECTIONS_IMAGE_TOPIC : /detections_image
    DETECTIONS_POSES_TOPIC : /test/detection_poses
    DETECTIONS_3D_TOPIC : /detections_3d
    DETECTIONS_ACTIVE_TOPIC : /detections_active
    DEBUG_IMAGE_TOPIC : /debug_image
    CAMERA_FRAME :  zed_left_camera_optical_frame
    TARGET_FRAME :  base_link
    YOLO_MODEL_PATH :  yolov5s.pt # FILE MOST BE IN MODEL FOLDER OF THE PACKAGE
    USE_ACTIVE_FLAG :  False
    DEPTH_ACTIVE :  True
    VERBOSE :  True
    USE_YOLO8 :  False
    FLIP_IMAGE :  False
    USE_ZED_TRANSFORM : True
    MIN_SCORE_THRESH :  0.75

