# ros2-build equivalent as dockerfile for local debugging
FROM ros:humble AS ros2-build

RUN ls -la

# RUN bash -c "source /opt/ros/humble/setup.sh" && ./.github/workflows/setup.sh && colcon build --symlink-install