float32 min_height
float32 max_height
---
geometry_msgs/PointStamped pt1
geometry_msgs/PointStamped pt2
geometry_msgs/PointStamped pt3
geometry_msgs/PointStamped pt4
geometry_msgs/PointStamped center
int32 health_response
