# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moondream_proto.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'moondream_proto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15moondream_proto.proto\x12\rimage_service\"\'\n\x11HelloWorldRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"6\n\x12HelloWorldResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2h\n\x11HelloWorldService\x12S\n\nHelloWorld\x12 .image_service.HelloWorldRequest\x1a!.image_service.HelloWorldResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moondream_proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOWORLDREQUEST']._serialized_start=40
  _globals['_HELLOWORLDREQUEST']._serialized_end=79
  _globals['_HELLOWORLDRESPONSE']._serialized_start=81
  _globals['_HELLOWORLDRESPONSE']._serialized_end=135
  _globals['_HELLOWORLDSERVICE']._serialized_start=137
  _globals['_HELLOWORLDSERVICE']._serialized_end=241
# @@protoc_insertion_point(module_scope)
