# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moondream_proto.proto
# Protobuf Python Version: 7.36.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    0,
    '',
    'moondream_proto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15moondream_proto.proto\x12\tmoondream\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"-\n\x14\x45ncodedImageResponse\x12\x15\n\rencoded_image\x18\x01 \x01(\x0c\"4\n\x0cQueryRequest\x12\x15\n\rencoded_image\x18\x01 \x01(\x0c\x12\r\n\x05query\x18\x02 \x01(\t\"\x1f\n\rQueryResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"A\n\x17\x46indObjectPointsRequest\x12\x15\n\rencoded_image\x18\x01 \x01(\x0c\x12\x0f\n\x07subject\x18\x02 \x01(\t\"#\n\x0bObjectPoint\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"Q\n\x18\x46indObjectPointsResponse\x12&\n\x06points\x18\x01 \x03(\x0b\x32\x16.moondream.ObjectPoint\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"7\n\rDetectRequest\x12\x15\n\rencoded_image\x18\x01 \x01(\x0c\x12\x0f\n\x07subject\x18\x02 \x01(\t\"Z\n\x0e\x44\x65tectedObject\x12\r\n\x05x_min\x18\x01 \x01(\x02\x12\r\n\x05y_min\x18\x02 \x01(\x02\x12\r\n\x05x_max\x18\x03 \x01(\x02\x12\r\n\x05y_max\x18\x04 \x01(\x02\x12\x0c\n\x04name\x18\x05 \x01(\t\"K\n\x0e\x44\x65tectResponse\x12*\n\x07objects\x18\x01 \x03(\x0b\x32\x19.moondream.DetectedObject\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\x32\xb3\x02\n\x10MoonDreamService\x12G\n\x0b\x45ncodeImage\x12\x17.moondream.ImageRequest\x1a\x1f.moondream.EncodedImageResponse\x12[\n\x10\x46indObjectPoints\x12\".moondream.FindObjectPointsRequest\x1a#.moondream.FindObjectPointsResponse\x12:\n\x05Query\x12\x17.moondream.QueryRequest\x1a\x18.moondream.QueryResponse\x12=\n\x06\x44\x65tect\x12\x18.moondream.DetectRequest\x1a\x19.moondream.DetectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moondream_proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=36
  _globals['_IMAGEREQUEST']._serialized_end=70
  _globals['_ENCODEDIMAGERESPONSE']._serialized_start=72
  _globals['_ENCODEDIMAGERESPONSE']._serialized_end=117
  _globals['_QUERYREQUEST']._serialized_start=119
  _globals['_QUERYREQUEST']._serialized_end=171
  _globals['_QUERYRESPONSE']._serialized_start=173
  _globals['_QUERYRESPONSE']._serialized_end=204
  _globals['_FINDOBJECTPOINTSREQUEST']._serialized_start=206
  _globals['_FINDOBJECTPOINTSREQUEST']._serialized_end=271
  _globals['_OBJECTPOINT']._serialized_start=273
  _globals['_OBJECTPOINT']._serialized_end=308
  _globals['_FINDOBJECTPOINTSRESPONSE']._serialized_start=310
  _globals['_FINDOBJECTPOINTSRESPONSE']._serialized_end=391
  _globals['_DETECTREQUEST']._serialized_start=393
  _globals['_DETECTREQUEST']._serialized_end=448
  _globals['_DETECTEDOBJECT']._serialized_start=450
  _globals['_DETECTEDOBJECT']._serialized_end=540
  _globals['_DETECTRESPONSE']._serialized_start=542
  _globals['_DETECTRESPONSE']._serialized_end=617
  _globals['_MOONDREAMSERVICE']._serialized_start=620
  _globals['_MOONDREAMSERVICE']._serialized_end=927
# @@protoc_insertion_point(module_scope)
