# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moondream_proto.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'moondream_proto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15moondream_proto.proto\x12\tmoondream\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"-\n\x14\x45ncodedImageResponse\x12\x15\n\rencoded_image\x18\x01 \x01(\x0c\"=\n\x13\x46indBeverageRequest\x12\x15\n\rencoded_image\x18\x01 \x01(\x0c\x12\x0f\n\x07subject\x18\x02 \x01(\t\",\n\x18\x42\x65veragePositionResponse\x12\x10\n\x08position\x18\x01 \x01(\t\"4\n\x0cQueryRequest\x12\x15\n\rencoded_image\x18\x01 \x01(\x0c\x12\r\n\x05query\x18\x02 \x01(\t\"\x1f\n\rQueryResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2\xec\x01\n\x10MoonDreamService\x12G\n\x0b\x45ncodeImage\x12\x17.moondream.ImageRequest\x1a\x1f.moondream.EncodedImageResponse\x12S\n\x0c\x46indBeverage\x12\x1e.moondream.FindBeverageRequest\x1a#.moondream.BeveragePositionResponse\x12:\n\x05Query\x12\x17.moondream.QueryRequest\x1a\x18.moondream.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moondream_proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=36
  _globals['_IMAGEREQUEST']._serialized_end=70
  _globals['_ENCODEDIMAGERESPONSE']._serialized_start=72
  _globals['_ENCODEDIMAGERESPONSE']._serialized_end=117
  _globals['_FINDBEVERAGEREQUEST']._serialized_start=119
  _globals['_FINDBEVERAGEREQUEST']._serialized_end=180
  _globals['_BEVERAGEPOSITIONRESPONSE']._serialized_start=182
  _globals['_BEVERAGEPOSITIONRESPONSE']._serialized_end=226
  _globals['_QUERYREQUEST']._serialized_start=228
  _globals['_QUERYREQUEST']._serialized_end=280
  _globals['_QUERYRESPONSE']._serialized_start=282
  _globals['_QUERYRESPONSE']._serialized_end=313
  _globals['_MOONDREAMSERVICE']._serialized_start=316
  _globals['_MOONDREAMSERVICE']._serialized_end=552
# @@protoc_insertion_point(module_scope)
