# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import moondream_proto_pb2 as moondream__proto__pb2


class MoonDreamServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EncodeImage = channel.unary_unary(
                '/moondream.MoonDreamService/EncodeImage',
                request_serializer=moondream__proto__pb2.ImageRequest.SerializeToString,
                response_deserializer=moondream__proto__pb2.EncodedImageResponse.FromString,
                _registered_method=True)
        self.FindObjectPoints = channel.unary_unary(
                '/moondream.MoonDreamService/FindObjectPoints',
                request_serializer=moondream__proto__pb2.FindObjectPointsRequest.SerializeToString,
                response_deserializer=moondream__proto__pb2.FindObjectPointsResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/moondream.MoonDreamService/Query',
                request_serializer=moondream__proto__pb2.QueryRequest.SerializeToString,
                response_deserializer=moondream__proto__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Detect = channel.unary_unary(
                '/moondream.MoonDreamService/Detect',
                request_serializer=moondream__proto__pb2.DetectRequest.SerializeToString,
                response_deserializer=moondream__proto__pb2.DetectResponse.FromString,
                _registered_method=True)


class MoonDreamServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def EncodeImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindObjectPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Detect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MoonDreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EncodeImage': grpc.unary_unary_rpc_method_handler(
                    servicer.EncodeImage,
                    request_deserializer=moondream__proto__pb2.ImageRequest.FromString,
                    response_serializer=moondream__proto__pb2.EncodedImageResponse.SerializeToString,
            ),
            'FindObjectPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.FindObjectPoints,
                    request_deserializer=moondream__proto__pb2.FindObjectPointsRequest.FromString,
                    response_serializer=moondream__proto__pb2.FindObjectPointsResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=moondream__proto__pb2.QueryRequest.FromString,
                    response_serializer=moondream__proto__pb2.QueryResponse.SerializeToString,
            ),
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=moondream__proto__pb2.DetectRequest.FromString,
                    response_serializer=moondream__proto__pb2.DetectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moondream.MoonDreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('moondream.MoonDreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MoonDreamService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EncodeImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moondream.MoonDreamService/EncodeImage',
            moondream__proto__pb2.ImageRequest.SerializeToString,
            moondream__proto__pb2.EncodedImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindObjectPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moondream.MoonDreamService/FindObjectPoints',
            moondream__proto__pb2.FindObjectPointsRequest.SerializeToString,
            moondream__proto__pb2.FindObjectPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moondream.MoonDreamService/Query',
            moondream__proto__pb2.QueryRequest.SerializeToString,
            moondream__proto__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moondream.MoonDreamService/Detect',
            moondream__proto__pb2.DetectRequest.SerializeToString,
            moondream__proto__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
