name: ros2-build 

on:
  pull_request:
  push:
    branches: ["**"]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:humble
    steps:
      - name: Create Workspace and checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Grant execute permissions
        run: |
          chmod +x ./.github/workflows/setup.sh
          chmod +x ./prebuild.sh

      - name: Build
        run: . /opt/ros/humble/setup.sh && ./.github/workflows/setup.sh && export GPD_INSTALL_DIR="$(pwd)/install/gpd" && colcon build --symlink-install
      